version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 415619022182.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t microservice:latest .
      - docker tag microservice:latest 415619022182.dkr.ecr.ap-southeast-1.amazonaws.com/microservice:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 415619022182.dkr.ecr.ap-southeast-1.amazonaws.com/microservice:latest

artifacts:
  files:
    - "**/*"
  discard-paths: yes
